# Generated by Django 3.1.12 on 2021-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0006_review_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='no_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
